<?php 

//Default Web URL: default was cms!

$content = $block->getContent();

$counter=1;
$fieldIdentifierPrefix = 'banner_';

while($counter < 10):

	$slideImage = $content->getImage($fieldIdentifierPrefix.'image_'.$counter);
	$slideColoredHeading = $content->getData($fieldIdentifierPrefix.'colored_heading_'.$counter);
	$slideHeading = $content->getData($fieldIdentifierPrefix.'heading_'.$counter);
	$slideBtnTxt = $content->getData($fieldIdentifierPrefix.'button_text_'.$counter);
	$slideBtnURL = $content->getData($fieldIdentifierPrefix.'button_url_'.$counter);


	

	if($slideImage){
?>
		<img src="<?php echo $slideImage; ?>" alt='' />
		<br /><br />
<?php
	}
	if($slideHeading || $slideColoredHeading){
?>
		<h1><?php echo($slideColoredHeading.$slideHeading); ?></h1>
<?php
	}

	if($slideBtnTxt && $slideBtnURL){
?>
		<a href="<?php echo $slideBtnURL; ?>" target="_blank"><?php echo $slideBtnTxt; ?></a>
		<br />		
<?php
	}
	$counter++;
endwhile;


$exploreImage = $content->getImage('explore_image');
$exploreTitle = $content->getData('explore_title');
$exploreBtnTxt = $content->getData('explore_button_text');
$exploreBtnURL = $content->getData('explore_button_url');

if($exploreImage){
?>
	<img src="<?php echo ($exploreImage); ?>" alt='' />
<?php	
}
if($exploreTitle){
?>	
	<h1><?php echo ($exploreTitle); ?></h1>
<?php
}
if($exploreBtnTxt && $exploreBtnURL){
?>
	<a href="<?php echo ($exploreBtnURL) ?>" target="_blank"><?php echo ($exploreBtnTxt); ?></a>
<?php
}



?>